# Generated by Django 5.2.7 on 2025-11-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='it_languages',
            field=models.CharField(blank=True, choices=[('python', 'python'), ('java', 'java'), ('ruby', 'ruby')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='languages',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('French', 'French'), ('Italian', 'Italian'), ('Russian', 'Russian')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='qualification',
            field=models.CharField(blank=True, choices=[('junior', 'junior'), ('senior', 'senior'), ('middle', 'middle')], max_length=100, null=True),
        ),
    ]
