# Generated by Django 5.2.7 on 2025-11-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.ImageField(upload_to='books/', verbose_name='image')),
                ('description', models.TextField(verbose_name='opisanie')),
                ('director', models.CharField(default='govnovoz', max_length=100, verbose_name='avtor')),
                ('genre', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Ужасы', 'Ужасы'), ('Драма', 'Драма'), ('Роман', 'Роман'), ('Фэнтези', 'Фэнтези'), ('История', 'История')], max_length=100, verbose_name='genre')),
                ('country', models.CharField(default='США', max_length=100, verbose_name='country')),
                ('pages', models.PositiveIntegerField(default=400, verbose_name='page count')),
                ('age', models.PositiveIntegerField(default=22222, verbose_name='age +')),
                ('language', models.CharField(max_length=100, verbose_name='language')),
                ('publishing_house', models.CharField(default='jopa press', max_length=100, verbose_name='house')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
